name: Check

on:
  pull_request

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Danger
        uses: docker://ghcr.io/danger/danger-kotlin:1.2.0
        with:
            args: --failOnErrors --no-publish-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: actions/setup-java@v3.13.0
        with:
          distribution: 'zulu'
          java-version-file: .ci-java-version

      - uses: gradle/wrapper-validation-action@v1.1.0

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.10.0
        with:
          gradle-version: wrapper

      - name: Run detekt
        run: ./detekt

  detektIos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: actions/setup-java@v3.13.0
        with:
          distribution: 'zulu'
          java-version-file: .ci-java-version

      - uses: gradle/wrapper-validation-action@v1.1.0

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.10.0
        with:
          gradle-version: wrapper

      - name: Build for iOS
        run: ./gradlew detektIosMain

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: actions/setup-java@v3.13.0
        with:
          distribution: 'zulu'
          java-version-file: .ci-java-version

      - uses: gradle/wrapper-validation-action@v1.1.0

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.10.0
        with:
          gradle-version: wrapper

      - name: Run checks
        run: ./gradlew lintRelease

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: actions/setup-java@v3.13.0
        with:
          distribution: 'zulu'
          java-version-file: .ci-java-version

      - uses: gradle/wrapper-validation-action@v1.1.0

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.10.0
        with:
          gradle-version: wrapper

      - name: Run checks
        run: ./gradlew allTests

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx4g -Xms512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1024m"
