name: Check

on:
  pull_request

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Danger
        uses: danger/kotlin@1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  assemble:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version-file: .ci-java-version

      - uses: gradle/wrapper-validation-action@v2.1.3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          gradle-home-cache-cleanup: true

      - name: Run assemble task
        run: ./gradlew assemble

  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version-file: .ci-java-version

      - uses: gradle/wrapper-validation-action@v2.1.3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          gradle-home-cache-cleanup: true

      - name: Run detekt
        run: ./gradlew detektAll

  detekt-apple:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version-file: .ci-java-version

      - uses: gradle/wrapper-validation-action@v2.1.3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          gradle-home-cache-cleanup: true

      - name: Run detekt for apple targets
        run: ./gradlew detektAppleMain detektAppleTest

  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Run ktlint
        run: ./format --no-format

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version-file: .ci-java-version

      - uses: gradle/wrapper-validation-action@v2.1.3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          gradle-home-cache-cleanup: true

      - name: Run Android lint
        run: ./gradlew lintRelease

  test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version-file: .ci-java-version

      - uses: gradle/wrapper-validation-action@v2.1.3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          gradle-home-cache-cleanup: true

      - name: Run tests
        run: ./gradlew allTests

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx4g -Xms512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1024m"
